[2024-05-20 15:02:35,645] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: custom_operator.custom_hello scheduled__2024-05-20T00:00:00+00:00 [queued]>
[2024-05-20 15:02:35,652] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: custom_operator.custom_hello scheduled__2024-05-20T00:00:00+00:00 [queued]>
[2024-05-20 15:02:35,653] {taskinstance.py:1376} INFO - 
--------------------------------------------------------------------------------
[2024-05-20 15:02:35,653] {taskinstance.py:1377} INFO - Starting attempt 1 of 1
[2024-05-20 15:02:35,653] {taskinstance.py:1378} INFO - 
--------------------------------------------------------------------------------
[2024-05-20 15:02:35,661] {taskinstance.py:1397} INFO - Executing <Task(HelloOperator): custom_hello> on 2024-05-20 00:00:00+00:00
[2024-05-20 15:02:35,664] {standard_task_runner.py:52} INFO - Started process 1469 to run task
[2024-05-20 15:02:35,666] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'custom_operator', 'custom_hello', 'scheduled__2024-05-20T00:00:00+00:00', '--job-id', '15', '--raw', '--subdir', 'DAGS_FOLDER/4-customoperator.py', '--cfg-path', '/tmp/tmpusz638d9', '--error-file', '/tmp/tmpt8hhkvrq']
[2024-05-20 15:02:35,666] {standard_task_runner.py:80} INFO - Job 15: Subtask custom_hello
[2024-05-20 15:02:35,705] {task_command.py:371} INFO - Running <TaskInstance: custom_operator.custom_hello scheduled__2024-05-20T00:00:00+00:00 [running]> on host c832426e9d7b
[2024-05-20 15:02:35,749] {taskinstance.py:1591} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=custom_operator
AIRFLOW_CTX_TASK_ID=custom_hello
AIRFLOW_CTX_EXECUTION_DATE=2024-05-20T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2024-05-20T00:00:00+00:00
[2024-05-20 15:02:35,750] {taskinstance.py:1909} ERROR - Task failed with exception
TypeError: execute() got an unexpected keyword argument 'context'
[2024-05-20 15:02:35,755] {taskinstance.py:1420} INFO - Marking task as FAILED. dag_id=custom_operator, task_id=custom_hello, execution_date=20240520T000000, start_date=20240520T150235, end_date=20240520T150235
[2024-05-20 15:02:35,764] {standard_task_runner.py:97} ERROR - Failed to execute job 15 for task custom_hello (execute() got an unexpected keyword argument 'context'; 1469)
[2024-05-20 15:02:35,803] {local_task_job.py:156} INFO - Task exited with return code 1
[2024-05-20 15:02:35,824] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
